#ifndef __DEFINES_H__
#define __DEFINES_H__

#define SECTOR_SIZE 512
#define SECTOR_FILES_SIZE 1024
#define MAP_SECTOR 0x100
#define FILES_SECTOR 0x101
#define SECTORS_SECTOR 0x103
#define ARGS_SECTOR 600
#define MAX_ARGS 8
#define ARGS_LENGTH 127
#define MAX_FILES 64
#define MAX_SECTORS_FILESECTOR 32
#define FILES_ENTRY_LENGTH 16
#define MAX_FILENAME 14
#define MAX_FILESECTOR 16
#define EMPTY 0x00
#define USED 0xFF
#define FILE_NOT_FOUND -1
#define FILE_HAS_EXIST -1
#define INSUFFICIENT_FILES -2
#define INSUFFICIENT_SECTORS -3
#define INVALID_FOLDER -4
#define NOT_DIRECTORY -5
#define FILE_IS_DIRECTORY -6
#define SAME_FOLDER -7

#define TRUE 1
#define FALSE 0

#endif